#!/bin/sh

# Initialise Vbuddy connection
//~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f counter.vcd

# run Verilator to translate Verilog into C++ including C++ testbench
verilator -Wall --cc --trace alu.sv  --exe alu_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Valu.mk Valu  # Capital 'V' in 'Valu.mk'

# run executable simulation file
obj_dir/Valu  # Capital 'V' in 'Valu'

#source ./doit.sh